name: mance
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  just_audio_background: ^0.0.1-beta.17
  video_player: ^2.10.0
  chewie: ^1.13.0
  just_audio: ^0.9.36
  share_plus: ^7.2.1
  path_provider: ^2.1.5
  flutter_inappwebview: ^6.1.5
  permission_handler: ^12.0.1
  sliding_up_panel: ^2.0.0+1
  icons_launcher: ^3.0.3
  loading_animation_widget: ^1.3.0
  photo_manager: ^3.7.1
  provider: ^6.1.5+1


icons_launcher:
  image_path: "assets/mance.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#ffffff"           # background color
  image: assets/mance.png      # your logo or image path
  android: true               # generate for Android
  ios: true                   # generate for iOS
  android_gravity: center     # logo position
  ios_content_mode: scaleAspectFit


flutter:

  uses-material-design: true

  assets:
    - assets/


